package com.projeto.uniClinicas.enums;

import java.util.stream.Stream;

public enum CidadesParaiba {
    PILOES("Pilões"),
    PITIMBU("Pitimbu"),
    PEDRA_LAVRADA("Pedra Lavrada"),
    MARCACAO("Marcação"),
    CONDADO("Condado"),
    BERNARDINO_BATISTA("Bernardino Batista"),
    SAO_JOSE_DA_LAGOA_TAPADA("São José da Lagoa Tapada"),
    ITAPOROROCA("Itapororoca"),
    CAMPO_DE_SANTANA("Campo de Santana"),
    BELEM_DO_BREJO_DO_CRUZ("Belém do Brejo do Cruz"),
    RIACHAO_DO_POCO("Riachão do Poço"),
    ARACAGI("Araçagi"),
    IMACULADA("Imaculada"),
    SERRARIA("Serraria"),
    RIACHO_DOS_CAVALOS("Riacho dos Cavalos"),
    GURINHEM("Gurinhém"),
    CACIMBAS("Cacimbas"),
    MATARACA("Mataraca"),
    PEDRAS_DE_FOGO("Pedras de Fogo"),
    MAMANGUAPE("Mamanguape"),
    PIANCO("Piancó"),
    SAPE("Sapé"),
    NOVA_FLORESTA("Nova Floresta"),
    ARARA("Arara"),
    CAJAZEIRAS("Cajazeiras"),
    CAPIM("Capim"),
    MANAIRA("Manaíra"),
    SAO_JOSE_DOS_RAMOS("São José dos Ramos"),
    CUITE("Cuité"),
    ASSUNCAO("Assunção"),
    POCO_DE_JOSE_DE_MOURA("Poço de José de Moura"),
    NOVA_OLINDA("Nova Olinda"),
    SOSSEGO("Sossêgo"),
    SERRA_REDONDA("Serra Redonda"),
    RIACHAO_DO_BACAMARTE("Riachão do Bacamarte"),
    TRIUNFO("Triunfo"),
    CUITE_DE_MAMANGUAPE("Cuité de Mamanguape"),
    ALAGOINHA("Alagoinha"),
    BARRA_DE_SANTA_ROSA("Barra de Santa Rosa"),
    MULUNGU("Mulungu"),
    SOLEDADE("Soledade"),
    JACARAU("Jacaraú"),
    CACHOEIRA_DOS_INDIOS("Cachoeira dos Índios"),
    NOVA_PALMEIRA("Nova Palmeira"),
    SAO_JOSE_DE_PIRANHAS("São José de Piranhas"),
    MAE_DAGUA("Mãe d'Água"),
    INGA("Ingá"),
    CATINGUEIRA("Catingueira"),
    TEIXEIRA("Teixeira"),
    ALAGOA_NOVA("Alagoa Nova"),
    PILAR("Pilar"),
    MATUREIA("Maturéia"),
    SANTA_RITA("Santa Rita"),
    DUAS_ESTRADAS("Duas Estradas"),
    CUITEGI("Cuitegi"),
    JUAREZ_TAVORA("Juarez Távora"),
    NAZAREZINHO("Nazarezinho"),
    REMIGIO("Remígio"),
    CABEDELO("Cabedelo"),
    RIO_TINTO("Rio Tinto"),
    BANANEIRAS("Bananeiras"),
    BOM_JESUS("Bom Jesus"),
    JUNCO_DO_SERIDO("Junco do Seridó"),
    SOLANEA("Solânea"),
    DAMIAO("Damião"),
    JURIPIRANGA("Juripiranga"),
    SOBRADO("Sobrado"),
    PILOEZINHOS("Pilõezinhos"),
    POCINHOS("Pocinhos"),
    COREMAS("Coremas"),
    SAO_JOSE_DO_BONFIM("São José do Bonfim"),
    SANTA_HELENA("Santa Helena"),
    SANTA_LUZIA("Santa Luzia"),
    BARAUNA("Baraúna"),
    BREJO_DOS_SANTOS("Brejo dos Santos"),
    BARRA_DE_SAO_MIGUEL("Barra de São Miguel"),
    PIRPIRITUBA("Pirpirituba"),
    BELEM("Belém"),
    AROEIRAS("Aroeiras"),
    SANTA_CRUZ("Santa Cruz"),
    RIACHAO("Riachão"),
    CAICARA("Caiçara"),
    SAO_JOSE_DO_SABUGI("São José do Sabugi"),
    MASSARANDUBA("Massaranduba"),
    NATUBA("Natuba"),
    OLIVEDOS("Olivedos"),
    BAYEUX("Bayeux"),
    PATOS("Patos"),
    JERICO("Jericó"),
    ARARUNA("Araruna"),
    PICUI("Picuí"),
    UIRAUNA("Uiraúna"),
    SAO_JOSE_DO_BREJO_DO_CRUZ("São José do Brejo do Cruz"),
    BREJO_DO_CRUZ("Brejo do Cruz"),
    PRINCESA_ISABEL("Princesa Isabel"),
    CASSERENGUE("Casserengue"),
    BOQUEIRAO("Boqueirão"),
    CABACEIRAS("Cabaceiras"),
    ALAGOA_GRANDE("Alagoa Grande"),
    LAGOA_SECA("Lagoa Seca"),
    CACIMBA_DE_AREIA("Cacimba de Areia"),
    PEDRA_BRANCA("Pedra Branca"),
    SAO_SEBASTIAO_DO_UMBUZEIRO("São Sebastião do Umbuzeiro"),
    ITATUBA("Itatuba"),
    DESTERRO("Desterro"),
    SANTA_TERESINHA("Santa Teresinha"),
    UMBUZEIRO("Umbuzeiro"),
    CRUZ_DO_ESPIRITO_SANTO("Cruz do Espírito Santo"),
    MATO_GROSSO("Mato Grosso"),
    SAO_BENTO("São Bento");

    private final String nome;

    CidadesParaiba(String nome) {
        this.nome = nome;
    }

    public String getNome() {
        return nome;
    }

    public static boolean nomeDeCidadeValido(String nomeCidade) {
        if (nomeCidade == null || nomeCidade.trim().isEmpty()) {
            return false;
        }
        return Stream.of(CidadesParaiba.values())
                .anyMatch(cidade -> cidade.getNome().equalsIgnoreCase(nomeCidade));
    }
}
